name: app_web_proyecto_final
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0-210.4.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core
  firebase_core: ^2.15.0
  #Firebase firestore
  cloud_firestore: ^4.8.4
  #Firebase storage
  firebase_storage: ^11.2.5
  #Firebase auth
  firebase_auth: ^4.8.0
  #google sing in
  google_sign_in: ^6.1.4
  #flutter facebook auth
  flutter_facebook_auth: ^6.0.3
  #provider  
  provider: ^6.0.1
  #dotted border
  dotted_border: ^2.0.0+2
  #image picker
  image_picker: ^0.8.4+4
  #uuid
  uuid: ^3.0.5
  #fluttertoast
  fluttertoast: ^8.0.7
  #file picker
  file_picker: ^5.3.4
  path: ^1.8.3
  path_provider: ^2.0.6
  universal_html: ^2.0.4
  http: ^1.1.0
  #carousel slider
  carousel_slider: ^4.2.1
  #card swiper
  card_swiper: ^3.0.1
  #flutter_rating_bar
  flutter_rating_bar: ^4.0.1
  #google maps
  google_maps_flutter: ^2.5.0
  location: ^5.0.3
  url_launcher: ^6.2.2
  intl_phone_field: ^3.2.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  shared_preferences: ^2.0.5
  iconly: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/mangas/shonen/
    - images/mangas/romance/
    - images/mangas/gore/
    - iconos/
    - assets/images/
